import { User, Project, Task } from "@/types";

export const USERS: User[] = [
  { id: "u1", name: "Jordan", color: "#00BCD4", initials: "JH" },
  { id: "u2", name: "Katie", color: "#E91E63", initials: "KT" },
  { id: "u3", name: "An", color: "#FFD600", initials: "AN" },
  { id: "u4", name: "Regan", color: "#9C27B0", initials: "RG" },
  { id: "u5", name: "Liger", color: "#FF5722", initials: "LG" },
];

export const INITIAL_PROJECTS: Project[] = [
  { id: "p1", name: "Marketing", color: "#00BCD4" },
  { id: "p2", name: "Partnerships", color: "#E91E63" },
  { id: "p3", name: "Product", color: "#FFD600" },
  { id: "p4", name: "Operations", color: "#9C27B0" },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "t1",
    title: "UX + Conversion Audit",
    client: "ACME Corp",
    sections: [
      { id: "s1a", heading: "Goal", content: "Figure out what's hurting conversions and give a prioritized fix list." },
      { id: "s1b", heading: "Scope", content: "Review 2 pages: / + /product (desktop + mobile)\nUX + conversion pass (CTAs, layout, forms, trust, readability)\nQuick competitor peek (2–3 sites)\nLook at GA4/Hotjar if access is provided" },
      { id: "s1c", heading: "Not Included", content: "Full-site audit, design comps, copywriting, implementation." },
      { id: "s1d", heading: "Deliverables", content: "Short audit doc with screenshots + \"what to change / why\"\nRanked backlog (quick wins + bigger items)\n30-min readout call" },
      { id: "s1e", heading: "Done When", content: "At least 10 findings\nTop 5 priorities clearly ranked (impact vs effort)\nQuick wins called out (can do in <1 day each)" },
      { id: "s1f", heading: "Needs", content: "Analytics access (optional) + contact for readout scheduling." },
    ],
    assignee_id: "u2",
    project_id: "p2",
    status: "doing",
    priority: 1,
    due_at: new Date(Date.now() + 3600000 * 4).toISOString(),
    created_by_id: "u1",
    created_via: "app_chat",
    drive_links: ["https://acme.com/", "https://acme.com/product"],
    notes: ["Katie has the latest case study deck", "ACME contact: sarah@acme.co"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t2",
    title: "Review Q1 campaign performance",
    sections: [
      { id: "s2a", heading: "Goal", content: "Pull analytics from all Q1 campaigns. Compare against KPIs and prepare summary for leadership." },
      { id: "s2b", heading: "Scope", content: "Google Ads, Meta Ads, LinkedIn campaigns\nEmail marketing sequences\nOrganic social performance" },
      { id: "s2c", heading: "Deliverables", content: "Executive summary deck (5-7 slides)\nRaw data export for finance" },
    ],
    assignee_id: "u1",
    project_id: "p1",
    status: "doing",
    priority: 1,
    due_at: new Date(Date.now() + 3600000 * 6).toISOString(),
    created_by_id: "u1",
    created_via: "manual",
    drive_links: [],
    notes: ["GA4 dashboard is updated", "Include social media metrics"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t3",
    title: "Finalize partnership deck for Globex",
    client: "Globex",
    sections: [
      { id: "s3a", heading: "Goal", content: "Update the partnership deck with new revenue projections and send to Globex team by EOD." },
      { id: "s3b", heading: "Deliverables", content: "Updated slide deck with ROI section\nOne-pager PDF for their exec team" },
    ],
    assignee_id: "u1",
    project_id: "p2",
    status: "doing",
    priority: 2,
    due_at: new Date(Date.now() + 3600000 * 8).toISOString(),
    created_by_id: "u2",
    created_via: "app_chat",
    drive_links: ["https://docs.google.com/presentation/d/example"],
    notes: ["Revenue projections from An", "Globex wants ROI section"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t4",
    title: "Update team onboarding docs",
    sections: [],
    assignee_id: "u3",
    project_id: "p4",
    status: "backlog",
    priority: 3,
    due_at: new Date(Date.now() + 86400000 * 2).toISOString(),
    created_by_id: "u1",
    created_via: "manual",
    drive_links: [],
    notes: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t5",
    title: "Design new landing page mockups",
    sections: [
      { id: "s5a", heading: "Scope", content: "Homepage hero redesign\nPricing page layout\nMobile-first approach" },
      { id: "s5b", heading: "Needs", content: "Brand guidelines from marketing team\nFinal copy from content team" },
    ],
    assignee_id: "u4",
    project_id: "p3",
    status: "waiting",
    priority: 2,
    due_at: new Date(Date.now() + 86400000 * 3).toISOString(),
    created_by_id: "u4",
    created_via: "manual",
    drive_links: [],
    notes: ["Waiting on brand guidelines from marketing"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t6",
    title: "Set up analytics tracking for new funnel",
    sections: [],
    assignee_id: "u5",
    project_id: "p1",
    status: "backlog",
    priority: 3,
    due_at: new Date(Date.now() + 86400000 * 5).toISOString(),
    created_by_id: "u1",
    created_via: "app_chat",
    drive_links: [],
    notes: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t7",
    title: "Send invoices for February",
    sections: [
      { id: "s7a", heading: "Scope", content: "3 outstanding invoices: Initech, Globex, ACME\nNet-30 terms on all" },
      { id: "s7b", heading: "Done When", content: "All 3 invoices sent via QuickBooks\nPayment reminders scheduled" },
    ],
    assignee_id: "u3",
    project_id: "p4",
    status: "doing",
    priority: 1,
    due_at: new Date(Date.now() + 3600000 * 2).toISOString(),
    created_by_id: "u3",
    created_via: "manual",
    drive_links: [],
    notes: ["3 outstanding invoices: Initech, Globex, ACME"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t8",
    title: "Prepare weekly team standup agenda",
    sections: [],
    assignee_id: "u4",
    project_id: "p4",
    status: "backlog",
    priority: 2,
    due_at: new Date(Date.now() + 86400000).toISOString(),
    created_by_id: "u1",
    created_via: "manual",
    drive_links: [],
    notes: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t9",
    title: "Research competitor pricing models",
    sections: [
      { id: "s9a", heading: "Goal", content: "Look at top 5 competitors and document their pricing tiers, features per tier, and any public case studies." },
    ],
    assignee_id: "u2",
    project_id: "p3",
    status: "done",
    priority: 3,
    due_at: new Date(Date.now() - 86400000).toISOString(),
    created_by_id: "u2",
    created_via: "manual",
    drive_links: [],
    notes: ["Completed analysis in shared doc"],
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t10",
    title: "Follow up with Initech on proposal",
    client: "Initech",
    sections: [
      { id: "s10a", heading: "Goal", content: "Send a follow-up email. They received our proposal last week and haven't responded." },
      { id: "s10b", heading: "Needs", content: "Confirmation on revised pricing before sending." },
    ],
    assignee_id: "u5",
    project_id: "p2",
    status: "waiting",
    priority: 1,
    due_at: new Date(Date.now() + 3600000 * 5).toISOString(),
    created_by_id: "u1",
    created_via: "app_chat",
    drive_links: [],
    notes: ["Contact: mike@initech.com", "Proposal sent Feb 3"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
